FROM continuumio/miniconda3:latest

#MAINTAINER CognitiveScale <devops@cognitivescale.com>
MAINTAINER Marmaduke <jmeppley@gmail.com>

# reduce image size by removing test data after clone
RUN git clone --recursive https://github.com/jmeppley/workflows /opt/workflows && \
  rm -rf /opt/workflows/test/data && \
  rm -rf /opt/workflows/tools/pymg/test

# reduce image size after conda run
#RUN conda install -c bioconda -c conda-forge "python=3.5" "snakemake<4" samtools last hmmer prinseq prodigal seqtk && \
#RUN conda env update -n root -f /opt/workflows/test/conda/annotate.yml && \
RUN conda env update -n root -f /opt/workflows/docker/annotation.reads/minimal.conda.yml && \
  conda clean --all -y

# copy in default config (can be ignored if new --configfile= argument passed in)
#  This lets us get locally modified config, not config from github
ADD ./config.yaml /default.config.yaml

WORKDIR /workdir

ENTRYPOINT [ "/usr/bin/tini", "--", "snakemake", "-s", "/opt/workflows/annotation.reads.snake", "--configfile", "/default.config.yaml", "-j", "20", "-p" ]

